### ISSUE TITLE
Gulp Environment Awareness

### ISSUE THREAD

**Issue by gbish** [wearearchitect/Frontend-Boilerplate#13]
It would be great if `gulpif` could be used as part of your boilerplate, which would help us prevent scenarios where dev only tasks are being called on a server, e.g. a notification generated by `gulp-notify`.

I have mentioned this to @MrRossBennett but thought I would put something here.

Here is an article I found on it: http://www.devworkflows.com/posts/using-gulp-if-to-create-dry-gulp-tasks/

This would make your Gulpfiles somewhat 'envronment aware' and would stop linting and other non-server required tasks from being run, and would make the difference between `--save` and `--save-dev` actually meaningful.

**Comment by MrRossBennett** [comment]
A grand idea. I am on the case, @gbish.

**Comment by onishiweb** [comment]
Sorted out in latest PR
