### ISSUE TITLE
Stance on Bower

### ISSUE THREAD

**Issue by lukewhitehouse** [wearearchitect/Frontend-Boilerplate#2]
This isn't really an issue, just a query.

I noticed that you've referenced a Sass version of Normalize within your `assets` folder and it got me thinking. Currently on the [framework](https://github.com/Mixd/frontend-framework) we use at Mixd we use Bower to bring through jQuery and normalize.scss. Afterwards, Normalize is brought in through Sass `@include` and jQuery is compiled into our `main.js` file through Grunt.

So, my question is whats your stance on using Bower for something like this?

**Comment by onishiweb** [comment]
It's something we're considering, I'm currently rewriting a lot of this and adding Gulp as a build tool, which in our default config does have Bower... so the next step is me just learning to use Bower properly and we're golden!

**Comment by lukewhitehouse** [comment]
@onishiweb Gotcha, that makes sense! We're in the mindset at the minute whether we really need Bower at all seeing as we're only pulling in jQuery/Normalize. Maybe theres a better solution, if you find something let me know! :)
